apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcscf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pcscf
  template:
    metadata:
      labels:
        app: pcscf
    spec:
      containers:
      - name: pcscf
        image: pcscf-cnf:1.0
        ports:
        - containerPort: 5060
